# Generated by Django 5.0.3 on 2024-04-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionitem_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='watchlist',
        ),
    ]
