# Generated by Django 5.0.3 on 2024-04-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_date_remove_watchlist_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
